executable               =  train_run.sh
output                   =  train_condor_out_$(ClusterId).out
error                    =  train_condor_error_$(ClusterId)_$(ProcId).err
log                      =  train_condor_log_$(ClusterId)_$(ProcId).log
should_transfer_files    =  YES
transfer_input_files     =  RUN.tar
transfer_output_files    =  models
when_to_transfer_output  =  ON_EXIT
request_memory           =  4 GB
request_GPUs             =  1
request_CPUs             =  1
queue
